version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "geoff-little-net"
s3_prefix = "geoff-little-net"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
