AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  geoff-little-net
 
Resources:
  GeoffLittleNetHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: geofflittle.net
