AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: geoff-little-net

Parameters:
  DomainName:
    Type: String
    Default: geofflittle.net

Resources:
  GeoffLittleNetHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name:
        Ref: DomainName

  NameServersLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./dist/nameServersLambda.handler
      Runtime: nodejs12.x
      Timeout: 900

  GeoffLittleCertificateNameServersCustomResource:
    Type: AWS::CloudFormation::CustomResource
    DependsOn:
      - GeoffLittleNetHostedZone
      - NameServersLambda
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - NameServersLambda
          - Arn
      HostedZone:
        Ref: GeoffLittleNetHostedZone

  GeoffLittleNetCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        Ref: DomainName
      ValidationMethod: DNS

  AcmDnsValidationLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./dist/acmDnsValidationLambda.handler
      Runtime: nodejs12.x
      Timeout: 900

  GeoffLittleCertificateValidationCustomResource:
    Type: AWS::CloudFormation::CustomResource
    DependsOn:
      - GeoffLittleNetHostedZone
      - AcmDnsValidationLambda
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - AcmDnsValidationLambda
          - Arn
      Certificate:
        HostedZone:
          Ref: GeoffLittleNetHostedZone
        DomainName:
          Ref: DomainName
        AlternativeNames:
          - Fn::Join:
              - ""
              - - dev.
                - DomainName
          - Fn::Join:
              - ""
              - - www.
                - DomainName
